bundler_args: --without development #rails-dev-boost: invalid byte sequence in US-ASCI

rvm:
  - 1.9.2

script:
 - "bundle exec rake db:drop db:create db:migrate --trace 2>&1"
 - "bundle exec rspec spec/controllers spec/helpers spec/liquids spec/models spec/observers" #except request

env: "LANG='en_US.UTF-8' RAILS_ENV='travis'"

#notifications:
#  recipients:
#    - mahb45@gmail.com
#    - liwh87@gmail.com
