rvm:
  - 1.9.2

script:
 - "bundle exec rake db:drop db:create db:migrate && bundle exec rspec spec --trace 2>&1"

env: "LANG='en_US.UTF-8' RAILS_ENV='test'"

notifications:
  recipients:
    - mahb45@gmail.com
    - liwh87@gmail.com
