defaults: &defaults
  templates:
    email:
      order_confirm:
        title: "\xE6\x82\xA8\xE5\x9C\xA8{{shop_name}}\xE7\x9A\x84\xE8\xAE\xA2\xE5\x8D\x95\xE4\xB8\x8B\xE5\x8D\x95\xE6\x88\x90\xE5\x8A\x9F"
        body: "\xE5\xB0\x8A\xE6\x95\xAC\xE7\x9A\x84{{customer.name}}\xEF\xBC\x9A \r\n   \xE6\x82\xA8\xE5\xA5\xBD,\xE6\x81\xAD\xE5\x96\x9C\xE6\x82\xA8\xE5\xB7\xB2\xE7\xBB\x8F\xE5\x9C\xA8{{shop_name}}\xE5\x95\x86\xE5\xBA\x97\xE8\xAE\xA2\xE8\xB4\xAD\xE5\x95\x86\xE5\x93\x81\xE6\x88\x90\xE5\x8A\x9F!,\xE8\xAE\xA2\xE5\x8D\x95\xE5\x8F\xB7\xEF\xBC\x9A{{order_number}}\xE3\x80\x82{% if requires_shipping %} \r\n   \xE6\x94\xB6\xE8\xB4\xA7\xE4\xBA\xBA\xE4\xBF\xA1\xE6\x81\xAF\xEF\xBC\x9A {{ shipping_address.name}}\xEF\xBC\x9A \r\n              {{ shipping_address.province}} {{ shipping_address.city}} {{ shipping_address.district}} {{ shipping_address.address1}} {% endif %} \r\n   \xE5\x8F\x91\xE5\x8D\x95\xE4\xBA\xBA\xE4\xBF\xA1\xE6\x81\xAF\xEF\xBC\x9A {{ billing_address.name }}\xEF\xBC\x9A\r\n              {{ billing_address.country }}{{ billing_address.province}} {{ billing_address.city}} {{ billing_address.district}} {{ billing_address.address1}} \r\n   \xE8\xAE\xA2\xE5\x8D\x95\xE5\x95\x86\xE5\x93\x81\xE6\x98\x8E\xE7\xBB\x86\xEF\xBC\x9A {% for line in line_items %} \r\n              {{ line.quantity }} x {{ line.title }}  \xE5\x8D\x95\xE4\xBB\xB7\xEF\xBC\x9A {{ line.price | money }} {% endfor %}\r\n   \xE8\xAE\xA2\xE5\x8D\x95\xE6\x80\xBB\xE9\xA2\x9D\xEF\xBC\x9A {{ total_price }}  | \xE5\x95\x86\xE5\x93\x81\xE6\x80\xBB\xE9\xA2\x9D\xEF\xBC\x9A {{ total_line_items_price }}  | \xE5\x8F\x91\xE8\xB4\xA7\xE6\x96\xB9\xE5\xBC\x8F\xE5\x8F\x8A\xE9\x87\x91\xE9\xA2\x9D\xEF\xBC\x9A {{ shipping_rate }}\r\n   \xE4\xBB\x98\xE6\xAC\xBE\xE6\x96\xB9\xE5\xBC\x8F\xEF\xBC\x9A {{ gateway }}   \r\n   \r\n   \xE8\xAE\xA2\xE5\x8D\x95\xE5\x95\x86\xE5\x93\x81\xE5\x8F\x91\xE8\xB4\xA7\xE5\x90\x8E\xEF\xBC\x8C\xE6\x88\x91\xE4\xBB\xAC\xE5\xB0\x86\xE5\x8F\x91\xE9\x80\x81\xE4\xB8\x80\xE5\xB0\x81\xE7\x94\xB5\xE5\xAD\x90\xE9\x82\xAE\xE4\xBB\xB6\xE7\xBB\x99\xE6\x82\xA8\xEF\xBC\x8C\xE7\xA1\xAE\xE8\xAE\xA4\xE5\x8F\x91\xE8\xB4\xA7\xE6\x97\xA5\xE6\x9C\x9F\xE3\x80\x81\xE5\x8F\x91\xE8\xB4\xA7\xE5\x86\x85\xE5\xAE\xB9\xE5\x92\x8C\xE9\x80\x81\xE8\xB4\xA7\xE6\x96\xB9\xE5\xBC\x8F\xE3\x80\x82\r\n\
          \r\n   \xE6\xAC\xA2\xE8\xBF\x8E\xE6\x82\xA8\xE5\x86\x8D\xE6\xAC\xA1\xE5\x88\xB0{{shop_name}}\xE8\xB4\xAD\xE7\x89\xA9\xEF\xBC\x8C\xE7\xA5\x9D\xE6\x82\xA8\xE8\xB4\xAD\xE7\x89\xA9\xE6\x84\x89\xE5\xBF\xAB\xEF\xBC\x81"

      new_order_notify:
        title: "[{{shop_name}}] \xE8\xAE\xA2\xE5\x8D\x95 {{ name }} , {{ billing_address.name }}\xE4\xB8\x8B\xE5\x8D\x95"
        body: "{{ shop_name }},\r\n\
          \r\n\
          {{ billing_address.name }} \xE6\x96\xB0\xE5\xA2\x9E\xE4\xBA\x86\xE8\xAE\xA2\xE5\x8D\x95({{ date | date: \"%b %d %I:%M%p\" }}). \r\n\
          \r\n\
          \xE4\xBB\x98\xE6\xAC\xBE\xE6\x96\xB9\xE5\xBC\x8F:\r\n  {{ gateway }}{% if requires_shipping %}\r\n\
          \r\n\
          \xE5\x8F\x91\xE9\x80\x81\xE6\x96\xB9\xE5\xBC\x8F: \r\n  {% for shipping_method in shipping_methods %}{{ shipping_method.title }}\r\n  {% endfor %}\r\n\
          \xE6\x94\xB6\xE8\xB4\xA7\xE4\xBA\xBA\xE4\xBF\xA1\xE6\x81\xAF:\r\n  {{ shipping_address.name }}\r\n  {{ shipping_address.country}} {{ shipping_address.province}} {{ shipping_address.city}} {{ shipping_address.district}} {{ shipping_address.address1}} , {{ shipping_address.zip }}\r\n  {{ shipping_address.phone }}{% endif %}\r\n\
          \r\n\
          \r\n\
          {% for line in line_items %}{{ line.quantity }}x {{line.title }}\t\t(sku: {{ line.sku }})\r\n\
          {% endfor %}"

      ship_confirm:
        title: "\xE8\xAE\xA2\xE5\x8D\x95 {{ name }} \xE5\x8F\x91\xE8\xB4\xA7\xE6\x8F\x90\xE9\x86\x92"
        body: "\xE5\xB0\x8A\xE6\x95\xAC\xE7\x9A\x84{{ billing_address.name }},\r\n\
          \r\n   \xE6\x82\xA8\xE6\x89\x80\xE8\xAE\xA2\xE8\xB4\xAD\xE7\x9A\x84\xE5\x95\x86\xE5\x93\x81 \xE5\xB7\xB2\xE7\xBB\x8F\xE5\x8F\x91\xE8\xB4\xA7\xE4\xBA\x86:\r\n\
          \r\n   {% for line in fulfillment.line_items %}{{ line.quantity }}x {{ line.title }}\r\n   {% endfor %}\r\n\
          \r\n\
          {% if requires_shipping %} \xE9\x80\x9A\xE8\xBF\x87 {% if fulfillment.tracking_company %} {{ fulfillment.tracking_company }} {% endif %}\xE5\x8F\x91\xE9\x80\x81\xE5\x88\xB0\xE4\xBB\xA5\xE4\xB8\x8B    \xE5\x9C\xB0\xE5\x9D\x80:\r\n\
          \r\n\
          \r\n\
          {% if fulfillment.tracking_number %}\r\n \xE8\xBF\x90\xE5\x8D\x95\xE5\x8F\xB7\xE4\xB8\xBA\xEF\xBC\x9A {{ fulfillment.tracking_number }}. \xE6\x82\xA8\xE5\x8F\xAF\xE4\xBB\xA5\xE9\x80\x9A\xE8\xBF\x87\xE4\xB8\x8B\xE9\x9D\xA2\xE7\x9A\x84\xE5\x9C\xB0\xE5\x9D\x80\xEF\xBC\x8C\xE6\x9F\xA5\xE8\xAF\xA2\xE6\x82\xA8\xE8\xB4\xA7\xE7\x89\xA9\xE7\x9A\x84\xE8\xBF\x90\xE9\x80\x81\xE7\x8A\xB6\xE6\x80\x81 :\r\n\
          \r\n\
          {{ fulfillment.tracking_url }}\r\n\
          \r\n\
          {% endif %}{% endif %}\r\n\
          \r\n  \xE6\xAC\xA2\xE8\xBF\x8E\xE6\x82\xA8\xE5\x86\x8D\xE6\xAC\xA1\xE5\x88\xB0{{shop_name}}\xE8\xB4\xAD\xE7\x89\xA9\xEF\xBC\x8C\xE7\xA5\x9D\xE6\x82\xA8\xE8\xB4\xAD\xE7\x89\xA9\xE6\x84\x89\xE5\xBF\xAB\xEF\xBC\x81"

      ship_update:
        title: Shipping update for order {{ name }}
        body: "\xE5\xB0\x8A\xE6\x95\xAC\xE7\x9A\x84 {{ billing_address.name }},\r\n\
          \r\n  \xE6\x82\xA8\xE7\x9A\x84\xE8\xAE\xA2\xE5\x8D\x95\xE5\x8F\xB7\xE4\xB8\xBA{{ name }}\xE7\x9A\x84\xE5\x95\x86\xE5\x93\x81\xE6\x9B\xB4\xE6\x94\xB9\xE4\xBA\x86\xE8\xBF\x90\xE9\x80\x81\xE4\xBF\xA1\xE6\x81\xAF\xEF\xBC\x9A\r\n\
          \r\n\
          {% for line in fulfillment.line_items %}{{ line.quantity }}x {{ line.title }}\r\n\
          {% endfor %}\r\n\
          \r\n \xE5\xAE\x83\xE4\xBB\xAC\xE5\xB0\x86\xE9\x80\x9A\xE8\xBF\x87{% if fulfillment.tracking_company %} {{ fulfillment.tracking_company }}{% endif %} \xE8\xBF\x90\xE9\x80\x81\xEF\xBC\x8C\xE8\xBF\x90\xE5\x8D\x95\xE5\x8F\xB7\xE4\xB8\xBA {{ fulfillment.tracking_number }}. \xE6\x82\xA8\xE5\x8F\xAF\xE4\xBB\xA5\xE9\x80\x9A\xE8\xBF\x87\xE4\xB8\x8B\xE9\x9D\xA2\xE9\x93\xBE\xE6\x8E\xA5\xE6\x9F\xA5\xE8\xAF\xA2\xEF\xBC\x9A\r\n\
          \r\n  {{ fulfillment.tracking_url }}\r\n\
          \r\n \xE6\xAC\xA2\xE8\xBF\x8E\xE6\x82\xA8\xE5\x86\x8D\xE6\xAC\xA1\xE5\x88\xB0{{shop_name}}\xE8\xB4\xAD\xE7\x89\xA9\xEF\xBC\x8C\xE7\xA5\x9D\xE6\x82\xA8\xE8\xB4\xAD\xE7\x89\xA9\xE6\x84\x89\xE5\xBF\xAB\xEF\xBC\x81"

      order_cancelled:
        title: "\xE8\xAE\xA2\xE5\x8D\x95 {{ name }} \xE5\x8F\x96\xE6\xB6\x88\xE6\x8F\x90\xE9\x86\x92"
        body: "\xE5\xB0\x8A\xE6\x95\xAC\xE7\x9A\x84 {{ billing_address.name }},\r\n\
          \r\n  \xE6\x82\xA8\xE7\x9A\x84\xE8\xAE\xA2\xE5\x8D\x95{{ name }}\xE5\xB7\xB2\xE5\x8F\x96\xE6\xB6\x88\xEF\xBC\x81 \xE5\xA6\x82\xE6\x9E\x9C\xEF\xBC\x8C\xE6\x82\xA8\xE5\xB7\xB2\xE4\xBB\x98\xE6\xAC\xBE\xEF\xBC\x8C\xE6\x88\x91\xE4\xBB\xAC\xE5\xB0\x86\xE4\xBC\x9A\xE6\x8A\x8A\xE6\xAC\xBE\xE9\xA1\xB9\xE8\xBF\x94\xE5\x9B\x9E\xE7\xBB\x99\xE6\x82\xA8\xEF\xBC\x81\r\n\
          \r\n  \xE5\xA6\x82\xE6\x9E\x9C\xEF\xBC\x8C\xE6\x82\xA8\xE6\x9C\x89\xE4\xBB\xBB\xE4\xBD\x95\xE7\x96\x91\xE9\x97\xAE\xEF\xBC\x8C\xE5\x8F\xAF\xE4\xBB\xA5\xE5\x9B\x9E\xE5\xA4\x8D\xE6\xAD\xA4\xE9\x82\xAE\xE4\xBB\xB6\xEF\xBC\x81\r\n  \r\n  \xE6\xAC\xA2\xE8\xBF\x8E\xE6\x82\xA8\xE5\x86\x8D\xE6\xAC\xA1\xE5\x88\xB0{{ shop_name }}\xE8\xB4\xAD\xE7\x89\xA9\xEF\xBC\x8C\xE7\xA5\x9D\xE6\x82\xA8\xE8\xB4\xAD\xE7\x89\xA9\xE6\x84\x89\xE5\xBF\xAB\xEF\xBC\x81\r\n"

      customer_account_activation:
        title: "{{ shop_name }}\xE5\xB8\x90\xE5\x8F\xB7\xE6\xBF\x80\xE6\xB4\xBB\xE6\x8F\x90\xE9\x86\x92"
        body: "\xE5\xB0\x8A\xE6\x95\xAC\xE7\x9A\x84{{ customer.name }},\r\n\
          \r\n  \xE6\x82\xA8\xE5\x9C\xA8{{ shop.name }}\xE7\x9A\x84\xE5\xB8\x90\xE5\x8F\xB7\xE5\xB7\xB2\xE7\xBB\x8F\xE5\x88\x9B\xE5\xBB\xBA.\r\n\
          \r\n  \xE8\xAF\xB7\xE7\x82\xB9\xE5\x87\xBB\xE4\xB8\x8B\xE9\x9D\xA2\xE7\x9A\x84\xE9\x93\xBE\xE6\x8E\xA5\xE5\xAE\x8C\xE6\x88\x90\xE6\xBF\x80\xE6\xB4\xBB\xE6\x93\x8D\xE4\xBD\x9C\xEF\xBC\x81 \r\n\
          \r\n  {{ customer.account_activation_url }}\r\n\
          \r\n  \r\n"

      customer_password_reset:
        title: "\xE5\xAF\x86\xE7\xA0\x81\xE5\x8F\x98\xE6\x9B\xB4"
        body: "\xE5\xB0\x8A\xE6\x95\xAC\xE7\x9A\x84 {{ customer.name }},\r\n\
          \r\n  \xE4\xBD\xA0\xE7\x94\xB3\xE8\xAF\xB7\xE4\xBA\x86\xE5\xAF\x86\xE7\xA0\x81\xE9\x87\x8D\xE7\xBD\xAE\xEF\xBC\x8C\xE8\xAF\xB7\xE7\x82\xB9\xE5\x87\xBB\xE4\xB8\x8B\xE9\x9D\xA2\xE7\x9A\x84\xE9\x93\xBE\xE6\x8E\xA5\xE9\x87\x8D\xE7\xBD\xAE\xE4\xBD\xA0\xE7\x9A\x84\xE5\xAF\x86\xE7\xA0\x81\r\n   {{ customer.reset_password_url }}\r\n  \r\n  \xE4\xB8\xBA\xE4\xBF\x9D\xE9\x9A\x9C\xE4\xBD\xA0\xE8\xB4\xA6\xE6\x88\xB7\xE7\x9A\x84\xE5\xAE\x89\xE5\x85\xA8\xE6\x80\xA7\xEF\xBC\x8C\xE4\xBB\xA5\xE4\xB8\x8A\xE9\x93\xBE\xE6\x8E\xA5\xE5\xB0\x86\xE5\x9C\xA8\xE4\xBD\xA0\xE5\xAF\x86\xE7\xA0\x81\xE4\xBF\xAE\xE6\x94\xB9\xE6\x88\x90\xE5\x8A\x9F\xE5\x90\x8E\xE5\xA4\xB1\xE6\x95\x88\xE3\x80\x82\r\n  {{ shop_name }}"

      customer_account_welcome:
        title: "\xE5\xB8\x90\xE5\x8F\xB7\xE6\xBF\x80\xE6\xB4\xBB\xE7\xA1\xAE\xE8\xAE\xA4\xE6\x8F\x90\xE9\x86\x92"
        body: "\xE5\xB0\x8A\xE6\x95\xAC\xE7\x9A\x84 {{ customer.name }},\r\n\
          \r\n  \xE6\x82\xA8\xE5\x9C\xA8{{ shop_name}}\xE7\x9A\x84\xE5\xB8\x90\xE5\x8F\xB7\xE5\xB7\xB2\xE6\xBF\x80\xE6\xB4\xBB\xEF\xBC\x81 \xE6\x82\xA8\xE5\x8F\xAF\xE4\xBB\xA5\xE6\x96\xB9\xE4\xBE\xBF\xE7\x9A\x84\xE4\xBD\xBF\xE7\x94\xA8\xE6\xAD\xA4\xE5\xB8\x90\xE5\x8F\xB7\xE5\x9C\xA8\xE6\x9C\xAC\xE5\xBA\x97\xE8\xB4\xAD\xE7\x89\xA9\xEF\xBC\x81\r\n  \r\n  \xE8\xB0\xA2\xE8\xB0\xA2\xEF\xBC\x81\r\n  {{ shop_name }}\r\n\
          \r\n"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults

travis:
  <<: *defaults
