defaults: &defaults
  mail_from: "ShopQi<noreply@shopqi.com>"
  domain:
    host: lvh.me
  wiki:
    relative_path: 'data/wiki'

development:
  <<: *defaults
  domain:
    host: lvh.me

test:
  <<: *defaults
  wiki:
    relative_path: 'data/wiki_test'

production:
  <<: *defaults
  domain:
    #host: lvh.me
    host: shopqi.com
