defaults: &defaults
  themes:
    client_id: 2f45ap2i4vklnz7fhkevvaawn
    client_secret: 2suo720v6k37q0qaardpdgx2v

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults

travis:
  <<: *defaults
